language: php

services:
    - docker

php:
    - 7.1

sudo: false

install:
    - travis_retry composer install

before_script:
    - sudo service mysql stop
    - docker-compose -f ./tests/docker-compose.yml up -d
    - php tests/wait-for-connection.php mysql
    - php tests/wait-for-connection.php pgsql
    - php tests/setup-mysql-schema.php
    - php tests/setup-pgsql-schema.php

script:
    - vendor/bin/phpunit --coverage-text

after_script:
    - docker-compose -f ./tests/docker-compose.yml down