language: php

services:
    - docker

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    allow_failures:
        - php: nightly

sudo: false

install:
    - travis_retry composer install

before_script:
    - sudo service mysql stop
    - sudo service postgresql stop
    - docker-compose -f ./tests/docker-compose.yml up -d
    - php tests/wait-for-connection.php mysql
    - php tests/wait-for-connection.php pgsql
    - php tests/setup-mysql-schema.php
    - php tests/setup-postgres-schema.php

script:
    - vendor/bin/psalm
    - vendor/bin/phpunit --coverage-text

after_script:
    - docker-compose -f ./tests/docker-compose.yml down
